import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generarTodo } from './generar_workflows_lab029.mjs';
import { crearWorkflowVerificadorRuntime } from './crear_workflow_verificador_runtime_lab029.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');
const workflowDir=path.join(root,'n8n','workflows','comercial'); let checks=0;
const check=(value,message)=>{assert.ok(value,message);checks++;};
const managementFailures=[];
const managementCheck=(value,message)=>{checks++;if(!value)managementFailures.push(message);};
const textOf=(node)=>JSON.stringify(node?.parameters||{});
const outgoing=(workflow,nodeName,kind='main')=>(workflow.connections[nodeName]?.[kind]||[]).flat().map(edge=>edge.node);
const incoming=(workflow,nodeName,kind='main')=>Object.entries(workflow.connections).filter(([,types])=>(types[kind]||[]).flat().some(edge=>edge.node===nodeName)).map(([name])=>name);
const reachable=(workflow,from,to,kind='main')=>{const pending=[from],seen=new Set();while(pending.length){const current=pending.shift();if(current===to)return true;if(seen.has(current))continue;seen.add(current);pending.push(...outgoing(workflow,current,kind));}return false;};
const mainReachableNames=(workflow)=>{const entries=workflow.nodes.filter(node=>/(?:webhook|trigger)$/i.test(node.type)&&!/respondToWebhook/i.test(node.type)).map(node=>node.name);const pending=[...entries],seen=new Set();while(pending.length){const current=pending.shift();if(seen.has(current))continue;seen.add(current);pending.push(...outgoing(workflow,current));}return seen;};
const allOutgoingEdges=(workflow,nodeName)=>Object.entries(workflow.connections[nodeName]||{}).flatMap(([kind,outputs])=>outputs.flat().map(edge=>({...edge,kind})));
for(const relative of execFileSync('git',['ls-tree','-r','--name-only','d1b3b8b99e5ca588c8a0b9d1fb6b76281effe399','--','n8n/workflows'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).filter(p=>/lab02[1-8]/i.test(p))){
  const current=execFileSync('git',['hash-object','--',relative],{cwd:root,encoding:'utf8'}).trim();const head=execFileSync('git',['rev-parse',`d1b3b8b99e5ca588c8a0b9d1fb6b76281effe399:${relative}`],{cwd:root,encoding:'utf8'}).trim();check(current===head,`histórico intacto: ${relative}`);
}
const generated=generarTodo();
for(const [key,value] of Object.entries(generated)){const actual=JSON.parse(fs.readFileSync(path.join(workflowDir,`lab029_${key}_rag_persistente.json`)));check(JSON.stringify(actual)===JSON.stringify(value),`export reproducible ${key}`);check(new Set(actual.nodes.map(n=>n.name)).size===actual.nodes.length,`nombres únicos ${key}`);}
const pub=generated.publico,internal=generated.interno,management=generated.gestion;
const postgresNodes=Object.values(generated).flatMap(workflow=>workflow.nodes.filter(node=>node.type==='n8n-nodes-base.postgres'));
check(postgresNodes.length===12&&postgresNodes.every(node=>node.credentials?.postgres?.id==='vpbKJO7irGofixTr'&&node.credentials?.postgres?.name==='Postgres account'),'todos los nodos PostgreSQL definitivos LAB-029 usan id y nombre exactos');
check(!/PostgreSQL documental LAB-029/.test(JSON.stringify(generated)),'exports LAB-029 sin referencias PostgreSQL antiguas');
for(const [key,workflow] of Object.entries(generated)){const names=new Set(workflow.nodes.map(node=>node.name));for(const [source,types] of Object.entries(workflow.connections)){check(names.has(source),`${key} origen de conexión existe: ${source}`);for(const outputs of Object.values(types))for(const output of outputs)for(const edge of output)check(names.has(edge.node),`${key} destino de conexión existe: ${edge.node}`);}}
check(!pub.nodes.some(n=>n.type.includes('vectorStoreInMemory')),'público sin memoria');
check(!pub.nodes.some(n=>n.name==='Recargar RAG al iniciar n8n'),'público sin recarga init');
const pubSearch=pub.nodes.find(n=>n.name==='Buscar información pública de la clínica');
check(pubSearch.type.includes('vectorStoreQdrant')&&pubSearch.parameters.qdrantCollection.value==='vetatiende_publico','colección pública compartida');
for(const fragment of ['metadata.clinic_id','metadata.visibility','metadata.status','active','metadata.version_id'])check(pubSearch.parameters.options.searchFilterJson.includes(fragment),`filtro público ${fragment}`);
const pubSerialized=JSON.stringify(pub),pubClinicAuthority=pub.nodes.find(n=>n.name==='Validar clínica pública PostgreSQL LAB-029'),pubClinicRestore=pub.nodes.find(n=>n.name==='Restaurar contexto clínica pública LAB-029'),pubClinicGate=pub.nodes.find(n=>n.name==='Clinic_id permitido');
check(!pubSerialized.includes('clinica_piloto_001'),'workflow Público final sin fallback ni hardcode de clínica piloto');
check(/clinics WHERE clinic_id=\$1 AND status='active'/.test(textOf(pubClinicAuthority))&&/\^\[a-z0-9\]/.test(textOf(pubClinicAuthority)),'clínica pública exige ID válido y clínica activa en PostgreSQL');
check(pubClinicAuthority?.alwaysOutputData===true&&pubClinicAuthority?.onError==='continueRegularOutput','fallo de autoridad clínica pública conserva salida fail-closed');
check(/clinic_id_permitido:\$json\.clinic_id_permitido===true/.test(pubClinicRestore?.parameters?.jsCode||'')&&/clinic_id_permitido === true/.test(textOf(pubClinicGate)),'contexto y autorización clínica pública usan booleano estricto');
check(reachable(pub,'Tiene session_id válido',pubClinicAuthority?.name)&&reachable(pub,pubClinicAuthority?.name,pubClinicGate?.name)&&!outgoing(pub,'Tiene session_id válido').includes(pubClinicGate?.name),'autoridad PostgreSQL precede validación clinic_id');
const pubPeluqueriaClinic=pub.nodes.find(n=>n.name==='Cargar configuración peluquería')?.parameters?.assignments?.assignments?.find(assignment=>assignment.name==='peluqueriaConfig')?.value||'';
check(pubPeluqueriaClinic.includes('clinic_id: String($json.clinic_id || "").trim()'),'configuración peluquería conserva clinic_id autorizado del contexto');
const intSearch=internal.nodes.find(n=>n.name==='Buscar conocimiento RAG interno');
check(intSearch.parameters.qdrantCollection.value==='vetatiende_interno','colección interna compartida');
for(const fragment of ['metadata.clinic_id','metadata.visibility','metadata.status','metadata.version_id'])check(intSearch.parameters.options.searchFilterJson.includes(fragment),`filtro interno ${fragment}`);
check(!intSearch.parameters.options.searchFilterJson.includes('metadata.access_level'),'Qdrant interno no usa filtro multi-value access_level incompatible con n8n 2.29.8');
const intConsolidate=internal.nodes.find(n=>n.name==='Consolidar contexto RAG interno');
check(/filtrarDocumentosInternosAutorizados\(\$input\.all\(\), solicitud\.niveles_acceso_permitidos\)/.test(intConsolidate?.parameters?.jsCode||'')&&/metadata\?\.access_level/.test(intConsolidate?.parameters?.jsCode||''),'access_level interno se filtra localmente antes de construir contexto para IA');
check(pubSearch.parameters.options.searchFilterJson.includes('value: "active"')&&!/indexed|staging|failed|superseded/.test(pubSearch.parameters.options.searchFilterJson),'público recupera solo active');
check(intSearch.parameters.options.searchFilterJson.includes('value: "active"')&&!/indexed|staging|failed|superseded/.test(intSearch.parameters.options.searchFilterJson),'interno recupera solo active');
check(pub.nodes.some(n=>n.name==='Leer versiones públicas activas LAB-029'),'público consulta autoridad PostgreSQL una vez');
check(internal.nodes.some(n=>n.name==='Leer versiones internas activas LAB-029'),'interno consulta autoridad PostgreSQL una vez');
check(!internal.nodes.some(n=>/Recargar RAG interno|Leer documentos RAG interno|Guardar documentos RAG interno/.test(n.name)),'interno sin recarga completa');
const internalMainReachable=mainReachableNames(internal);
const internalUnexpectedOrphans=internal.nodes.filter(node=>{if(internalMainReachable.has(node.name))return false;const edges=allOutgoingEdges(internal,node.name);return !(edges.length>0&&edges.every(edge=>edge.kind.startsWith('ai_')&&internalMainReachable.has(edge.node)));});
check(internalUnexpectedOrphans.length===0,`interno sin nodos huérfanos/no alcanzables: ${internalUnexpectedOrphans.map(node=>node.name).join(', ')}`);
check(management.nodes.filter(n=>n.type==='n8n-nodes-base.postgres').length>=3,'gestión usa PostgreSQL canónico');
check(management.nodes.some(n=>n.type.includes('vectorStoreQdrant')),'gestión carga Qdrant');
check(!management.nodes.some(n=>n.type==='n8n-nodes-base.webhook'),'gestión sin webhook público');
check([pub,internal,management].every(workflow=>workflow.active===false),'exports LAB-029 permanecen inactivos');
const managementNode=(id,name)=>management.nodes.find(node=>node.id===id)||management.nodes.find(node=>node.name===name);
const validateNode=managementNode('lab029-validate','Validar contrato documental LAB-029'),stageNode=managementNode('lab029-stage','Crear versión staging PostgreSQL LAB-029');
const activeReadNode=managementNode('lab029-active-v2','Consultar versión activa PostgreSQL LAB-029'),stageRestoreNode=managementNode('lab029-stage-context-v2','Restaurar contexto tras staging PostgreSQL LAB-029');
const qdrantInsert=management.nodes.find(node=>node.type.includes('vectorStoreQdrant')&&node.parameters?.mode==='insert');
const documentLoader=management.nodes.find(node=>node.name==='Cargar contenido documental real LAB-029');
const stageContext=management.nodes.find(node=>node.name==='Restaurar contexto tras staging PostgreSQL LAB-029'),qdrantContext=management.nodes.find(node=>node.name==='Restaurar contexto tras Qdrant LAB-029'),stagingValidation=management.nodes.find(node=>node.name==='Validar recuperación staging Qdrant LAB-029');
const noChangeNode=managementNode('lab029-no-change'),activationNode=managementNode('lab029-activate');
const beforeStage=management.nodes.filter(node=>node.id!==stageNode?.id&&reachable(management,node.name,stageNode?.name));
const beforeNoChange=management.nodes.filter(node=>node.id!==noChangeNode?.id&&reachable(management,node.name,noChangeNode?.name));
const afterStage=management.nodes.filter(node=>node.id!==stageNode?.id&&reachable(management,stageNode?.name,node.name));
const triggerOwnedEvents=['staged','validated','activated','failed','rollback'];

managementCheck(outgoing(management,validateNode?.name).some(name=>{const node=management.nodes.find(n=>n.name===name);return /if|switch|filter|stopAndError/i.test(node?.type||'')&&/contrato_valido/.test(textOf(node));}),'01 contrato_valido bloquea inputs inválidos antes de PostgreSQL/Qdrant');
managementCheck(beforeStage.some(node=>/version_id/.test(textOf(node))&&/(randomUUID|uuid|\$execution|Date\.now|generate|crear|concat|`)/i.test(textOf(node))),'02 version_id se genera antes de insertar document_versions');
managementCheck(beforeNoChange.some(node=>/event_id/.test(textOf(node))&&/(randomUUID|uuid|\$execution|Date\.now|generate|crear|concat|`)/i.test(textOf(node))),'03 event_id se genera antes de registrar no_changes');
managementCheck(management.nodes.some(node=>/(INSERT INTO\s+(?:vetatiende_documental\.)?documents|crear.{0,20}documento|documento.{0,20}(nuevo|no existente))/is.test(`${node.name} ${textOf(node)}`)),'04 existe manejo explícito para documento nuevo/no existente');
managementCheck(Boolean(qdrantInsert)&&incoming(management,qdrantInsert.name,'ai_document').length>0&&management.nodes.some(node=>/(content|contenido|binary|document)/i.test(`${node.name} ${textOf(node)}`)&&!/(source_file|content_hash)/i.test(textOf(node))&&reachable(management,node.name,qdrantInsert.name)),'05 Qdrant recibe documentos/contenido real para embeddings');
check(documentLoader?.parameters?.dataType==='json'&&documentLoader.parameters.jsonMode==='expressionData'&&documentLoader.parameters.jsonData==='={{ $json.document_content }}','Data Loader carga únicamente document_content como pageContent');
check(documentLoader.parameters.options.metadata.metadataValues.map(value=>value.name).join(',')==='clinic_id,document_id,version_id,version_number,document_type,visibility,content_hash,updated_at,source_file,access_level,status','Data Loader conserva metadata documental completa');
check(textOf(stageContext).includes("$('Decidir staging documental LAB-029').first().json")&&textOf(qdrantContext).includes("$('Restaurar contexto tras staging PostgreSQL LAB-029').first().json")&&![stageContext,qdrantContext].some(node=>textOf(node).includes("$('Preparar contexto e IDs LAB-029').first().json")),'contexto posterior a staging conserva identidad persistida');
check(textOf(stagingValidation).includes("$('Restaurar contexto tras staging PostgreSQL LAB-029').first().json")&&textOf(stagingValidation).includes('payload.content')&&textOf(stagingValidation).includes('Number(m.version_number)===Number(b.version_number)'),'validación staging exige contenido Qdrant y version_number coherente');
check(/MAX\(history\.version_number\)/.test(textOf(activeReadNode))&&/active\.version_id AS active_version_id/.test(textOf(activeReadNode)),'lectura de versión obtiene active y máximo histórico');
check(/ON CONFLICT \(document_id,content_hash\) DO UPDATE/.test(textOf(stageNode))&&/document_versions\.status='failed'/.test(textOf(stageNode))&&/RETURNING version_id,document_id,version_number/.test(textOf(stageNode)),'staging reutiliza failed por hash y devuelve identidad persistida');
check(textOf(stageRestoreNode).includes("$('Decidir staging documental LAB-029').first().json")&&/\.\.\.base,\.\.\.\$json/.test(textOf(stageRestoreNode)),'contexto staging prioriza valores RETURNING de PostgreSQL');
check(textOf(stagingValidation).includes("$('Restaurar contexto tras staging PostgreSQL LAB-029').first().json")&&textOf(stagingValidation).includes('String(m.version_id)===String(b.version_id)'),'validación staging usa identidad persistida');
const persistedStageConsumers=['Recuperar staging Qdrant LAB-029','Qdrant nueva versión a active LAB-029','Activar versión validada PostgreSQL LAB-029','Marcar staging failed PostgreSQL LAB-029','Marcar staging failed Qdrant LAB-029'];
check(persistedStageConsumers.every(name=>textOf(management.nodes.find(node=>node.name===name)).includes('Restaurar contexto tras staging PostgreSQL LAB-029')),'tramo staging usa version_id persistido en recuperación, activación y fallo');
managementCheck(Boolean(qdrantInsert)&&management.nodes.some(node=>{const value=`${node.name} ${textOf(node)}`;return (/vectorStoreQdrant/.test(node.type)&&node.parameters?.mode!=='insert'||/httpRequest/.test(node.type)&&/points\/scroll/.test(value))&&/clinic_id/.test(value)&&/document_id/.test(value)&&/version_id/.test(value)&&/staging/.test(value)&&reachable(management,qdrantInsert.name,node.name)&&reachable(management,node.name,activationNode?.name); }),'06 staging se recupera/valida desde Qdrant antes de activarse');
const failedHandlers=afterStage.filter(node=>node.type==='n8n-nodes-base.postgres'&&/UPDATE\s+(?:vetatiende_documental\.)?document_versions[\s\S]*status\s*=\s*'failed'/i.test(textOf(node)));
managementCheck(failedHandlers.length>0&&afterStage.some(node=>/error|fallo|fail/i.test(`${node.name} ${textOf(node)}`)&&failedHandlers.some(handler=>reachable(management,node.name,handler.name))),'07 errores posteriores a staging conducen explícitamente a status=failed');
managementCheck(failedHandlers.some(node=>/WHERE[\s\S]*(version_id|status\s*=\s*'staging')/i.test(textOf(node)))&&!afterStage.some(node=>/UPDATE[\s\S]*document_versions[\s\S]*status\s*=\s*'failed'[\s\S]*status\s*=\s*'active'/i.test(textOf(node))),'08 el manejo de falla preserva la versión active anterior');
const qdrantStateNodes=afterStage.filter(node=>node.type.includes('qdrant')||/qdrant/i.test(node.name));
managementCheck(/activate_document_version/.test(textOf(activationNode))&&qdrantStateNodes.some(node=>/active/.test(textOf(node)))&&qdrantStateNodes.some(node=>/superseded/.test(textOf(node))),'09 activación sincroniza nueva active y anterior superseded en PostgreSQL/Qdrant');
const rollbackNodes=management.nodes.filter(node=>/rollback/i.test(`${node.name} ${textOf(node)}`));
managementCheck(rollbackNodes.some(node=>/rollback_document_version/.test(textOf(node)))&&rollbackNodes.some(node=>/qdrant/i.test(`${node.type} ${node.name} ${textOf(node)}`)&&/active/.test(textOf(node))&&/superseded/.test(textOf(node))),'10 rollback coordina estados PostgreSQL/Qdrant');
const rollbackValidation=management.nodes.find(node=>node.name==='Validar recuperación después del rollback Qdrant LAB-029');
check(['Restaurar contexto rollback LAB-029','payload.content','m.clinic_id','m.document_id','m.version_id','b.target_version_id','m.status','active','m.content_hash','b.content_hash'].every(fragment=>textOf(rollbackValidation).includes(fragment)),'validación rollback exige punto objetivo active con clínica, documento, contenido y hash coherentes');
managementCheck(!management.nodes.some(node=>{const value=textOf(node);return /INSERT INTO\s+(?:vetatiende_documental\.)?document_events/i.test(value)&&triggerOwnedEvents.some(type=>new RegExp(`['"]${type}['"]`).test(value));}),'11 no duplica eventos generados por triggers/funciones PostgreSQL');
const contextKeys=['clinic_id','document_id','version_id','coleccion'];
managementCheck([stageNode,qdrantInsert].every(node=>node&&outgoing(management,node.name).every(next=>{const target=management.nodes.find(n=>n.name===next);const value=textOf(target);return contextKeys.every(key=>value.includes(key)||value.includes(`$('`)||value.includes(`$(\\"`));})),'12 conserva o restaura contexto tras nodos PostgreSQL/Qdrant');
const qdrantHttp=management.nodes.filter(node=>node.type==='n8n-nodes-base.httpRequest'&&/Qdrant/.test(node.name));
check(qdrantHttp.every(node=>/LAB029_QDRANT_URL/.test(textOf(node))&&node.parameters.authentication==='predefinedCredentialType'&&node.parameters.nodeCredentialType==='qdrantApi'),'Qdrant HTTP usa URL externa y credencial, sin secretos exportados');
check(qdrantHttp.every(node=>node.typeVersion===4.2&&node.parameters.method==='POST'&&node.parameters.sendBody===true&&node.parameters.contentType==='json'&&node.parameters.specifyBody==='json'&&typeof node.parameters.jsonBody==='string'&&node.parameters.jsonBody.startsWith('={')&&!/JSON\.stringify/.test(node.parameters.jsonBody)&&!/^=\{\{ \(\{/.test(node.parameters.jsonBody)&&!('body' in node.parameters)&&!('rawContentType' in node.parameters)),'HTTP Request Qdrant Gestión usa JSON nativo evaluable por n8n 2.29.8 sin envoltura JavaScript');
check(qdrantHttp.every(node=>{try{const body=JSON.parse(node.parameters.jsonBody.slice(1)),expressions=[];const visit=value=>{if(typeof value==='string'&&/^\{\{[\s\S]+\}\}$/.test(value))expressions.push(value);else if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==='object')Object.values(value).forEach(visit);};visit(body);return expressions.length>=3&&expressions.every(value=>{new Function('$json','$env','$',`return (${value.slice(2,-2).trim()});`);return true;});}catch{return false;}}),'jsonBody Qdrant Gestión es JSON literal evaluable y solo sus valores dinámicos contienen expresiones válidas');
check(qdrantHttp.filter(node=>/payload|active|failed|superseded/i.test(`${node.name} ${node.parameters.url}`)).every(node=>['metadata.clinic_id','metadata.document_id','metadata.version_id'].every(key=>node.parameters.jsonBody.includes(key))),'mutaciones Qdrant usan filtro estricto clinic/document/version');
check(management.nodes.some(node=>node.name==='Restaurar versión anterior active Qdrant LAB-029')&&reachable(management,'Marcar staging failed PostgreSQL LAB-029','Restaurar versión anterior active Qdrant LAB-029'),'falla de activación restaura active anterior en Qdrant');
check(management.nodes.some(node=>node.name==='Compensar rollback PostgreSQL LAB-029')&&reachable(management,'Recuperar versión después del rollback Qdrant LAB-029','Compensar rollback PostgreSQL LAB-029'),'fallo de validación rollback compensa PostgreSQL y Qdrant');
const sql=fs.readFileSync(path.join(root,'scripts/lab029/migraciones/001_dominio_documental.sql'),'utf8')+fs.readFileSync(path.join(root,'scripts/lab029/migraciones/002_activacion_rollback.sql'),'utf8');
for(const table of ['clinics','documents','document_versions','document_events'])check(new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`).test(sql),`tabla ${table}`);
for(const fragment of ["visibility IN ('public', 'internal')","status IN ('staging', 'active', 'superseded', 'failed')",'one_active_version_per_document','UNIQUE (document_id, version_number)','content_hash','REFERENCES clinics','REFERENCES documents','activate_document_version','rollback_document_version'])check(sql.includes(fragment),`integridad SQL ${fragment}`);
for(const fragment of ['FOREIGN KEY (document_id, version_id)','REFERENCES document_versions(document_id, version_id)','CREATE TRIGGER clinics_updated_at BEFORE UPDATE','CREATE TRIGGER documents_updated_at BEFORE UPDATE',"NEW.updated_at := clock_timestamp()","record_version_event(NEW.version_id, 'staged')","record_version_event(NEW.version_id, 'validated')","record_version_event(NEW.version_id, 'failed')","record_version_event(p_version_id, 'activated')","record_version_event(p_target_version_id, 'rollback')"])check(sql.includes(fragment),fragment);
const activateNode=management.nodes.find(n=>n.id==='lab029-activate');
check(!activateNode.parameters.query.includes('INSERT INTO'),'activación auditada exclusivamente por PostgreSQL');
check(management.nodes.find(n=>n.id==='lab029-no-change').parameters.query.includes("'no_changes'"),'no_changes responsabilidad gestión');
const serialized=JSON.stringify(generated)+sql;
for(const pattern of [/postgres(?:ql)?:\/\/[^\s]+:[^\s]+@/i,/-----BEGIN [A-Z ]*PRIVATE KEY-----/,/\b(?:sk-|gsk_)[A-Za-z0-9_-]{20,}/])check(!pattern.test(serialized),`sin secreto ${pattern}`);
check(!/aiven/i.test(serialized),'sin proveedor hardcodeado');
const verifier=crearWorkflowVerificadorRuntime({name:'LAB029_TEST_validator',path:'lab029-test-validator',prefix:'LAB029_TEST_validator',headerCredentials:{httpHeaderAuth:{name:'test'}}});
const verifierEntry=verifier.nodes.find(node=>node.type==='n8n-nodes-base.webhook'),verifierResponse=verifier.nodes.find(node=>node.type==='n8n-nodes-base.respondToWebhook'),verifierReachable=mainReachableNames(verifier);
check(verifierReachable.has(verifierResponse.name),'verificador Respond to Webhook alcanzable desde webhook raíz');
check(verifier.nodes.filter(node=>node.name!==verifierResponse.name).every(node=>outgoing(verifier,node.name).length>0),'verificador sin ramas runtime terminales antes de Respond');
check(verifier.nodes.filter(node=>node.type==='n8n-nodes-base.postgres').every(node=>node.alwaysOutputData===true&&node.onError==='continueRegularOutput'),'verificador preserva item con cero resultados/error PostgreSQL');
check(!verifier.nodes.some(node=>node.type==='n8n-nodes-base.httpRequest')&&!/qdrant/i.test(textOf(verifier)),'verificador temporal depende únicamente de PostgreSQL');
check(verifier.nodes.find(node=>node.name==='Evaluar assertions runtime LAB-029').alwaysOutputData===true,'verificador Code contractual preserva un item');
check(incoming(verifier,verifierResponse.name).length===1&&outgoing(verifier,verifierResponse.name).length===0,'verificador Respond recibe ruta única y es único terminal');
check(verifierEntry.parameters.responseMode==='responseNode'&&/summary/.test(verifierResponse.parameters.responseBody),'verificador usa responseNode y contrato JSON explícito');
const verifierCode=verifier.nodes.find(node=>node.name==='Evaluar assertions runtime LAB-029').parameters.jsCode;
check(['staged','validated','activated','no_changes','failed','rollback'].every(value=>verifierCode.includes(value))&&/content_hash\]\)\.sort\(\)/.test(verifierCode),'verificador valida estados/eventos PostgreSQL y fingerprint canónico');
check(fs.readFileSync(path.join(root,'.gitignore'),'utf8').includes('private-storage/'),'storage privado fuera de Git');
const hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(workflowDir,'lab028_avisos_comerciales_contextuales_post_reserva.json'))).digest('hex');
const result={ok:managementFailures.length===0,checks,management_contract:{passed:12-managementFailures.length,failed:managementFailures.length,failures:managementFailures},workflows:{publico:pub.nodes.length,interno:internal.nodes.length,gestion:management.nodes.length},lab028_sha256:hash};
process.stdout.write(`${JSON.stringify(result,null,2)}\n`);
if(managementFailures.length)throw new AggregateError(managementFailures,'workflow gestión LAB-029 incumple contrato estático');
